---

- name: Check for existence of cluster in db.
  register: cluster_check
  ansible.builtin.shell: "set -o pipefail && sacctmgr -n list cluster | cut -f 4 -d ' '"
  become: true
  become_user: root

- name: Set cluster_check_boolean
  ansible.builtin.set_fact:
      __cluster_not_setup: false
  when: cluster_check.stdout == "cluster"

- name: Create the slurmdbd cluster
  ansible.builtin.command: sacctmgr -i -n add cluster {{ __slurm_cluster_name }}
  become: true
  become_user: root
  notify:
    - reload slurmdbd
  when: __cluster_not_setup
