---

- name: Check for existence of cluster in db.
  ansible.builtin.shell: |
    set -o pipefail
    sacctmgr -n list cluster | awk '{print $1}'
  args:
    executable: /bin/bash
  become: true
  become_user: root
  register: cluster_check
  changed_when: false

- name: Set cluster_check_boolean
  ansible.builtin.set_fact:
      __cluster_not_setup: false
  when: cluster_check.stdout == "cluster"

- name: Create the slurmdbd cluster
  ansible.builtin.command: sacctmgr -i -n add cluster {{ __slurm_cluster_name }}
  become: true
  become_user: root
  notify:
    - Reload slurmdbd
  when: __cluster_not_setup
